### ISSUE TITLE
Result of the dbt_date.convert_timestamp() is always timestamp_ntz

### ISSUE THREAD

**Issue by ImBharathwaj** [calogica/dbt-date#125]
### Result I got
I was using **dbt_date.convert_timezone()** which result an outcome with timestamp without time zone offset in the form of **timestamp_ntz**

### Result I am looking for
I am looking to get the outcome in the form of timestamp_tz with time zone offset

I have tried every possible things which I could do. But nothing was working
Please let me know any other possible ways

**Comment by clausherther** [comment]
Which database platform are you using, and which version of dbt-date and dbt?

**Comment by ImBharathwaj** [comment]
I am using snowflake as data warehouse, dbt version as 1.7.3 with snowflake plugin version as 1.7.1
I need to store timestamp data in various formats and data-types liKkeVARCHAR, TIMESTAMP_TZ, TIMESTAMP.NTZ) as a datatype of TIMESTAMP_TZ with timezone in the form of UTC with offset of +0000

Please let me know the feasibility of the my requirement.

**Comment by clausherther** [comment]
In dbt-date, we cast the result of `convert_timezone` to whatever data type `dbt.type_timestamp()` returns on the platform, which on Snowflake is timestamp_ntz.
```sql
{% macro default__convert_timezone(column, target_tz, source_tz) -%}
convert_timezone('{{ source_tz }}', '{{ target_tz }}',
    cast({{ column }} as {{ dbt.type_timestamp() }})
)
{%- endmacro -%}
```

If you're on Snowflake, have you tried just using `convert_timezone` directly, without dbt-date?
https://docs.snowflake.com/en/sql-reference/functions/convert_timezone
