### ISSUE TITLE
Changes to dispatch in dbt v0.20

### ISSUE THREAD

**Issue by jtcohen6** [calogica/dbt-date#34]
As promised, what follows is effectively the same as https://github.com/calogica/dbt-expectations/issues/78.

### Required code change

We've made a change to `adapter.dispatch`: Instead of passing a `_get_namespaces()` macro to the `packages` arg, you should pass the name of this package (as a string) to the `macro_namespace` arg, which is now the second positional argument.

In practice, this just looks like switching each macro like:
https://github.com/calogica/dbt-date/blob/370d472f13933437db53bb885e334b016d458a70/macros/calendar_date/date_part.sql#L1-L3

To:
```sql
{% macro date_part(datepart, date) -%}
      {{ adapter.dispatch('date_part', 'dbt_date') (datepart, date) }}
{%- endmacro %} 
```

I hope this could be as simple as Find + Replace for `packages = dbt_date._get_utils_namespaces()` &rarr; `'dbt_date'`. If you prefer more explicit syntax, you could also make this:
```sql
{% macro date_part(datepart, date) -%}
      {{ adapter.dispatch(macro_name = 'date_part', macro_namespace = 'dbt_date') (datepart, date) }}
{%- endmacro %} 
```

### For the README

If a user wishes to override/shim this package, instead of defining a var named `dbt_expectations_dispatch_list` (or `dbt_utils_dispatch_list`), they should now define [a config](https://next.docs.getdbt.com/reference/project-configs/dispatch-config) in `dbt_project.yml`, for instance:
```yml
dispatch:
  - macro_namespace: dbt_date
    search_order: ['my_project', 'dbt_date']  # enable override
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']  # shim for spark
```

### Notes

This change is in dbt v0.19.2 as well. **Both v0.19.2 and v0.20.0 have backwards compatibility for the old syntax**, so there's no huge rush to upgrade. The old syntax will start raising a deprecation warning in v0.20. As soon as you do upgrade to the new syntax, you'll need to require `dbt >= 0.19.2` (or just `>=0.20.0`, for simplicity, since you're already making compatibility changes in #69).

See also:
- https://github.com/fishtown-analytics/dbt/issues/3383
- https://next.docs.getdbt.com/reference/dbt-jinja-functions/dispatch

**Comment by clausherther** [comment]
@jerco getting a weird test failure on 1 out of a few tests using dbt 0.20.0rc1 . Even though this integration tests returns (based on the test SQL from the logs)
```
| failures | should_warn | should_error |
|----------|-------------|--------------|
| 0        | false       | false        |
```

the CLI reports 
```
Failure in test dbt_utils_expression_is_true_test_dates_time_stamp_dbt_date_from_unixtimestamp_unix_epoch_ (models/test_dates.yml)
  Got 2 results, configured to fail if != 0
```
This is only one where that's the case and I can't figure out why. Any ideas? 

This is the relevant query from the logs:
```sql
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      with meet_condition as (

    select * from postgres.dbt_date_integration_tests.test_dates where 1=1

),
validation_errors as (

    select
        *
    from meet_condition
    
    where not(time_stamp = to_timestamp(unix_epoch))

)

select *
from validation_errors


      
    ) dbt_internal_test
```
which when run through postgres, returns
```
| failures | should_warn | should_error |
|----------|-------------|--------------|
| 0        | false       | false        |
```

**Comment by jtcohen6** [comment]
Very weird! I don't know why it would say 2 when the test query is clearly returning `failures: 0`.

I'm planning to release dbt-utils 0.7.0 today, which will be 0.20 compatible. If you can open up a PR with dbt v0.20 / dbt-utils v0.7 compatibility, I can take it for a spin.
