### ISSUE TITLE
Not compatible with latest versions of dbt and dbt_utils

### ISSUE THREAD

**Issue by cmcnicoll** [calogica/dbt-date#4]
Ran into these issues when trying to upgrade from dbt 0.16.0 to 0.18.0. Thanks for your time.

$ dbt seed --full-refresh
Running with dbt=0.18.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_date
 - dbt_utils

$ dbt deps
Running with dbt=0.18.0
Encountered an error:
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.6.2', '>=0.2.0', '<0.3.0']

**Comment by clausherther** [comment]
@cmcnicoll just had a chance to fix in the latest release, 0.2.0. Sorry about the delay!
