### ISSUE TITLE
0.4.0 lacks support for dbt 0.21

### ISSUE THREAD

**Issue by drernie** [calogica/dbt-date#48]
This version of dbt is not supported with the 'dbt_date' package.
      Installed version of dbt: =0.21.0
      Required version of dbt for 'dbt_date': ['>=0.20.0', '<0.21.0']
    Check the requirements for the 'dbt_date' package, or run dbt again with --no-version-check

**Comment by clausherther** [comment]
Hi @drernie the latest release supports 0.21, it just isn't on dbt hub yet. Hopefully they'll have it updated by tomorrow!
https://github.com/calogica/dbt-date/releases/tag/0.4.1

**Comment by clausherther** [comment]
Closed via #47
