### ISSUE TITLE
`this_week` macro calls a non-existent utils macro `this_week_start`

### ISSUE THREAD

**Issue by joellabes** [calogica/dbt-date#55]
Repro: 

compile `{{ dbt_date.this_week() }}` in a dbt Cloud scratchpad

Observed: 
```
Server error: Compilation Error in rpc request (from remote system)
'dict object' has no attribute 'this_week_start'

> in macro this_week (macros/calendar_date/this_week.sql)
> called by rpc request (from remote system)
```

[this_week_start doesn't exist](https://github.com/dbt-labs/dbt-utils/search?q=this_week_start) in dbt utils, and I don't remember it ever being there (it doesn't appear in the changelog either).

I think that either the macro should be removed from dbt-date altogether (apparently no one's calling it anyway since it doesn't do anything) or implemented in dbt-date

**Comment by clausherther** [comment]
Ha. Who wrote this crap! Wait, that was me. What was I thinking. I bet this is the result of a disastrous find/replace operation. And lack of testing. I'll remove it. Thanks!
