### ISSUE TITLE
Allow negative shift year for fiscal periods

### ISSUE THREAD

**Issue by boludo00** [calogica/dbt-date#57]
Some fiscal years are tracked differently, needing support of a negative shift year.
For example, in one scenario a `date_day` of `2022-01-01` is actually in the fiscal year 2023. The generated `fiscal_year_number` would need to be `2023` in this case. This can be achieved by suppling a negative shift value however, doing so causes the rendered SQL to be interpreted as a comment:

```sql
{{ dbt_date.get_fiscal_periods(ref('dates'), year_end_month=1, week_start_day=2, shift_year=-1) }}
```

```sql
d.year_number -{{ shift_year }} as fiscal_year_number,
```

Gets rendered as:
```sql
d.year_number --1 as fiscal_year_number, this is a comment 👀 
```
Not sure how everyone else's use case differs, but I thought I would bring it up in case there are more similar scenarios out there.

**Comment by clausherther** [comment]
Good call, thanks for raising that issue!
