### ISSUE TITLE
dbt_metrics requires different names for date functionality. 

### ISSUE THREAD

**Issue by sisu-callum** [calogica/dbt-date#59]
Hey Claus! 

I was playing around with the `dbt_metrics` package recently released by dbt_labs and noticed that there are some requirements for date field names that are slightly different from `dbt_date`. Specifically:

- `date_week`, which in dbt_date is called `week_start_date`
- `date_month` which in dbt_date is called `month_start_date`
- `date_quarter` which in dbt_date is called `quarter_start_date`
- `date_year` which in dbt_date is called `year_start_date`

Not sure if you'd want to rename those columns as that could be a breaking change for people using the package. But maybe introduce a duplicate column with those names so it works easily with the metrics package?

Or you can suggest that people rename the columns (which is what I'm doing in the meantime).

**Comment by sisu-callum** [comment]
Best I understand, the way that the date grouping is applied with the `dbt_metrics` package relies on there being specific fields at the time grains specified in the metric yml definition. So if you've included `[day,week,month]` the underlying query when trying to aggregate at those levels will look for the fields `date_day`, `date_week`, and `date_month`. 

As for renaming those columns, I'm aligned in that it would create more of an issue than it would solve. I think a shim or alternative version would work OR maybe include new columns with those names that are nothing more than duplicate values of the respective date fields. All of those are options that I think would work just fine.

Not a high priority issue but figured I'd flag to you after doing some testing last week!

**Comment by Jake-Gillberg** [comment]
+1 to this!

> I think a shim or alternative version would work OR maybe include new columns with those names that are nothing more than duplicate values of the respective date fields. All of those are options that I think would work just fine.

I would support (and maybe even implement) any of these options if you have a preference. Another option might be something like a defaulted-off `metrics_compatibility` argument to `get_date_dimension`.
