### ISSUE TITLE
Version 0.5.5 is bad

### ISSUE THREAD

**Issue by judahrand** [calogica/dbt-date#67]
New release seems to be causing this compilation error

```
16:40:45  Encountered an error:
Compilation Error
  unexpected '}', expected ')'
    line 2
      {{ return(default__convert_timezone(column, target_tz, source_tz) }}
```

**Comment by clausherther** [comment]
Hi @judahrand thanks for reporting! We just pushed #66 to address this. See also #64

**Comment by clausherther** [comment]
version 0.5.6 is out and should be on package hub shortly.
