### ISSUE TITLE
Deprecated Functionality re dbt_utils

### ISSUE THREAD

**Issue by pkanter** [calogica/dbt-date#74]
After adding dbt-date to my packages, I got the following error upon running dbt dept.  I am using the package provided at dbt hub, 

packages:
  - package: calogica/dbt_date
    version: 0.2.4
```
13:16:23  [WARNING]: Deprecated functionality
The `fishtown-analytics/dbt_utils` package is deprecated in favor of
`dbt-labs/dbt_utils`. Please update your `packages.yml` configuration to use
`dbt-labs/dbt_utils` instead.
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency. Code: 10006
```

**Comment by clausherther** [comment]
Hi @pkanter, the current version of dbt-date is 0.5.7, not sure where you found instructions to pin your version to 0.2.4.
See: https://github.com/calogica/dbt-date#dbt-date

The best way to install is to specify a range of minor releases so you don't have to worry about keeping up with patch releases, e.g.
```yaml
packages:
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]
```

**Comment by pkanter** [comment]
Thank you!
