### ISSUE TITLE
week_of_year starts on mondays instead of sundays

### ISSUE THREAD

**Issue by MJ-jorisverzuu** [calogica/dbt-date#75]
A colleague of mine noticed that the week_of_year field is not correct. According to the documentation the week_of_year field should start its week on a sunday, however it starts its week on monday.
![image](https://user-images.githubusercontent.com/91115782/169225698-5f5ff15d-bbee-43a2-a8cd-ceb75a7adfd3.png)

**Comment by MJ-jorisverzuu** [comment]
Hi @clausherther, thank you for your response.

- The data warehouse platform we're using is Snowflake
- DBT-date version: 0.5.7
- DBT version: 1.0

**Comment by clausherther** [comment]
Gotcha. Would you mind checking what the parameter value for `WEEK_START` is on your Snowflake instance? (run `show prameters`).
The default is 0, which means Sunday, but you might have this overriden to `1` in which case all the non-ISO week macros would probably still use ISO logic. 
```
Defines the first day of the week:
0: legacy Snowflake behavior; 1: Monday .. 7: Sunday.
```
On my instance, it's set to 0 and I also set it to 0 for the session only, and no matter what I do, the raw SQL returns the same for either regular or ISO week logic. So, for now I assume this may be a Snowflake bug.
For example,
```sql
with dates as (
  select date'2015-01-03' as date_day 
  union all 
  select date'2015-01-04' as date_day 
  union all 
  select date'2015-01-05' as date_day 
  union all 
  select date'2015-01-06' as date_day 
)
select 
    date_day,
    dayname(date_day) as day_of_week_name,
    date_part('dayofweek', date_day) as day_of_week,
    case
        when date_part('dayofweek', date_day) = 7 then 1
        else date_part('dayofweek', date_day) + 1
    end as day_of_week_adj,
    date_part('dayofweekiso', date_day) as day_of_week_iso,
    cast(date_part('week', date_day) as int) as week_of_year,
    weekofyear(date_day) as week_of_year_alternate,
    cast(date_part('weekiso', date_day) as int) as iso_week_of_year,
    weekiso(date_day) as iso_week_of_year_alternate
from
    dates
order by 1;
```
returns week `2` for `2015-01-05` for either version.

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/7342749/169908126-83d4df5a-ab0b-43b6-b8d8-268ac3e6cde2.png">

**Comment by MJ-jorisverzuu** [comment]
On my instance the WEEK_START value is also set to 0. 
Thank you for figuring this out! For now I will just let everyone know to use the ISO week logic.

**Comment by dalerking** [comment]
I believe that I've found a similar issue in that when I pass in a date into dbt_date.n_days_ago() of 12/31/1984 and 7 days ago and then pass the returned date into dbt_date.iso_week_of_year(), I don't get the correct week. It doesn't appear to take leap year into account.  The date 12/24/1984 when starting on Monday (ISO), should return 53 when it is actually returning 52.  It turns out that this same scenario occurs with 12/31/2012 and 12/31/2040 which are also leap years.

Data warehouse:  Snowflake
dbt_date version:  0.5.7

I recreated the issue with the following:

```
WITH 

date_spine AS (
    {{ dbt_utils.date_spine(
        start_date="to_date('01/01/1984', 'mm/dd/yyyy')",
        datepart="day",
        end_date="to_date('01/01/1985', 'mm/dd/yyyy')")
    }}
),

stage AS (
    SELECT
        ds.date_day,
        {{ dbt_date.n_days_ago(7, 'ds.date_day') }} AS date_day_7ago,
        {{ dbt_date.iso_week_of_year('date_day_7ago') }} AS iso_week_of_year_7ago
    FROM date_spine ds
),

final AS (
    SELECT
        s.date_day,
        s.date_day_7ago,
        s.iso_week_of_year_7ago
    FROM stage s
)

SELECT * FROM final ORDER BY date_day
```

**Comment by clausherther** [comment]
I think this has more to do with Snowflake than the macros. On Snowflake we basically call 
```sql
date_part('week', date'2012-12-31')
```
which returns `1` on my instance with default settings (ISO/Monday weeks). Matches what my calendar app thinks as well.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/7342749/185416278-f9a7a1ed-a882-42ad-ab2d-6b0a5d641f4e.png">
