### ISSUE TITLE
Add string-to-date macros

### ISSUE THREAD

**Issue by fivetran-jamie** [calogica/dbt-date#80]
In the [dbt google play source package](https://github.com/fivetran/dbt_google_play_source/blob/0404f10901bcf32772c6ecaecf482cb38f6b30f0/models/stg_google_play__earnings.sql#L46-L62), i implemented some hefty string-to-date and string-to-timestamp logic for Bigquery, Snowflake, Spark, Redshift, and Postgres users. 

I was originally going to move the logic to a macro in `dbt_fivetran_utils` but was wondering if there would be interest in folding it in here. The logic currently works on dates that are stored like `'Apr 1, 2022'` and times that are like `'1:23:45 AM PDT'` (though it ignores the timezone). I could see a path forward with one or two macros, each with an `input-format` argument (like `'MMM d, yyyy'` and `'h:mm:ss am tz'`), and the string would be parsed dynamically based on its input format. 

expanding the functionality would definitely be a good bit of work, so wanted to check first if this would be of interest. otherwise will just put the macro as is in our fivetran utils package 🤠

**Comment by clausherther** [comment]
Hi @fivetran-jamie! Thanks for this! I'm all for centralizing date logic as much possible into the fewest packages possible, so I love your suggestion and would be interested in a PR. 
We'd want to think about how to make these work for the other platforms we support (postgres, Snowflake). Can definitely help with that!
