### ISSUE TITLE
Add macros for date_from_timestamp

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [calogica/dbt-date#82]
We just released a new v1.0.0 for our [Ad Reporting](https://github.com/fivetran/dbt_ad_reporting) package last month and had to utilize a [macro](https://github.com/fivetran/dbt_ad_reporting/blob/main/macros/get_date_from_timestamp.sql) in order to extract date from a timestamp. 

It looked like some databases can automatically interpret timestamp strings/objects and have functionality to extract dates while others need to be explicitly converted to timestamps before the extraction is possible, so if this is something that could be of interest to add to `dbt-date`, I'd love to hear recommendations on best approaches here and happy to kickstart a PR if that's the case.

**Comment by clausherther** [comment]
Hi @fivetran-sheringuyen! That sounds very useful indeed. We have somewhat of a precedent in dbt-date, with macros like `from_unixtimestamp` and `to_unixtimestamp`. 
FYI, we only test (and thus support) BigQuery, Snowflake and postgres, so we might not be able to support your spark implementation. Looking forward to a PR! (Happy to help if needed)

**Comment by clausherther** [comment]
Btw, there's a somewhat related [PR](https://github.com/calogica/dbt-date/pull/81) from @fivetran-jamie that's going a bit stale. I don't think they quite cover the same scope, just wanted to highlight that in case you all want to chat and compare notes ;)

**Comment by clausherther** [comment]
Another thing to consider is, how much of this overlaps with `date_trunc`? https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#date_trunc

**Comment by clausherther** [comment]
So, this is sort of depends on what you mean by 'date'. Do we mean stripping a timestamp off its time portion, or returning a `date` type? For example, `select date_trunc(current_timestamp(), DAY)` will return something like `2022-09-28 00:00:00 UTC` but won't convert to `date`. I think this is acceptable in most cases and it's on the caller to do the cast if necessary. What do you think?

**Comment by fivetran-sheringuyen** [comment]
From my experience (and general needs) I would like to strip the timestamp to only leave the date AND convert it to a date object.

**Comment by fivetran-sheringuyen** [comment]
So it sounds like this would be a PR that makes sense for dbt-date. I will go ahead and make a first pass PR for it!
