### ISSUE TITLE
Remove current_timestamp in favor of dbt_core

### ISSUE THREAD

**Issue by sti0** [calogica/dbt-date#87]
`dbt-core` already provides a required `current_timestamp` [macro](https://docs.getdbt.com/guides/advanced/adapter-development/3-building-a-new-adapter#required-macros) for each adapter. 

So I ask you if there is any need to have this [own macro](https://github.com/calogica/dbt-date/blob/4c81a6e32037062db3099483659b08c5932ffece/macros/calendar_date/now.sql#L5) in `dbt-date`.

This forces user to overwrite the macro even when the adapter already serves this macro with the right implementation.

**Comment by clausherther** [comment]
Nope we don't need it! Was just waiting for dbt-core to implement this so we can deprecate it.

(Btw, you shouldn't have to overwrite anything? One is `dbt_date.current_timestamp()` and one is just `current_timestamp()`?)

**Comment by clausherther** [comment]
That shouldn't make any difference in how the macros are resolved. Are you getting any errors?

**Comment by sti0** [comment]
Yes, because the code is resolved to `current_timestamp::TIMESTAMP` which is not valid in the Exasol dialect (which I'm using). 
For example if I use `{{ current_timestamp() }}` (which points to the adapter implementation) I receive `current_timestamp` which is valid in this dialect.

**Comment by clausherther** [comment]
We don't support Exasol in either dbt-date or dbt-expectations, so I can't verify that. Hopefully that'll work once #88 is merged and released.

**Comment by clausherther** [comment]
(For adapters other than Postgres, Snowflake and BigQuery, I'd recommend using or creating a shim package, similar to https://hub.getdbt.com/dbt-msft/tsql_utils/latest/ to adjust macros to your specific adapter.)

**Comment by sti0** [comment]
Yeah I know, we had to adjust some things. And I recently checked our overwrites and ask my self why we are doing this bc its already implemented in the adapter so I came up with this ticket :)
Thanks for the quick fix

**Comment by clausherther** [comment]
@sti0 0.6.3 should be on package hub within the next hour or so. Hope that helps.

**Comment by sti0** [comment]
@clausherther works like expected. Thanks
