### ISSUE TITLE
dbt 0.19.0 is not supported

### ISSUE THREAD

**Issue by cmcnicoll** [calogica/dbt-date#9]
Specifying --no-version-check allows dbt seed/run/test to complete successfully. Please update require-dbt-version when you get a chance.  Thanks for your time.

$ dbt seed --full-refresh
Running with dbt=0.19.0
Encountered an error:
Runtime Error
  Failed to read package: Runtime Error
    This version of dbt is not supported with the 'dbt_date' package.
      Installed version of dbt: =0.19.0
      Required version of dbt for 'dbt_date': ['>=0.18.0', '<0.19.0']
    Check the requirements for the 'dbt_date' package, or run dbt again with --no-version-check

**Comment by clausherther** [comment]
@cmcnicoll thanks for reminding me! I also cut a new release 0.2.3 with this change.
